app/__init__.py
# -*- coding: utf-8 -*-
# @Author: Sam Zhang
# @Date:   2020-04-10 20:05:32
# @Last Modified by:   Sam Zhang
# @Last Modified time: 2020-04-14 11:17:08

from flask import Flask
from .extensions import *
from uuid import uuid4


def create_app():
    app = Flask(__name__)

    app.config['SECRET_KEY'] = str(uuid4())

    bootstrap.init_app(app)

    from  .main import main as main_bp
    app.register_blueprint(main_bp)

    from .baidu import baidu as baidu_bp
    app.register_blueprint(baidu_bp)

    from .google import google as google_bp
    app.register_blueprint(google_bp)

    from .api import api as api_bp
    app.register_blueprint(api_bp)

    return app

app/api/__init__.py
# -*- coding: utf-8 -*-
# @Author: Sam Zhang
# @Date:   2020-04-14 11:01:56
# @Last Modified by:   Sam Zhang
# @Last Modified time: 2020-04-14 12:41:25

from flask import Blueprint

api = Blueprint('api', __name__, url_prefix='/api')

from . import baidu, google

app/baidu/__init__.py
# -*- coding: utf-8 -*-
# @Author: Sam Zhang
# @Date:   2020-04-10 20:06:38
# @Last Modified by:   Sam Zhang
# @Last Modified time: 2020-04-14 11:08:07

from flask import Blueprint

baidu = Blueprint('baidu', __name__, url_prefix='/baidu')

from . import views

app/baidu/views.py
# -*- coding: utf-8 -*-
# @Author: Sam Zhang
# @Date:   2020-04-10 20:06:43
# @Last Modified by:   Sam Zhang
# @Last Modified time: 2020-04-14 11:28:00

from . import baidu
from flask import render_template, request, redirect, url_for, abort, make_response, session
from app.utils import baidu_search, google_search
from urllib.parse import unquote


@baidu.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        q = request.form.get('query')
        pn = request.args.get('page')
        if pn is None:
            pn = 0
        return redirect(url_for('baidu.search', q=q, page=pn))
    return render_template('baidu/index.html')


@baidu.route('/s/', methods=['GET', 'POST'])
def search():
    q = request.args.get('q')
    if not q:
        return redirect(url_for('main.index'))
    pn = int(request.args.get('page', 0))
    return render_template('baidu/search.html', keyword=q, cur=pn)

@baidu.route('/s/s/', methods=['GET', 'POST'])
def search_s():
    q = request.args.get('q')
    pn = int(request.args.get('page', 0))
    results = baidu_search(word=str(q), pn=int(pn))
    try:
        pages = results[1]
        pre_results = results[2]
        results = results[0]
    except IndexError:
        results = []
        pre_results = []
        pages = 0
    pages_ = []
    for i in range(0, pages):
        pages_.append(i)
    return render_template('baidu/search_s.html', keyword=unquote(q, 'utf-8'), results=results, pages=pages_, cur=pn, pre_results=pre_results)

app/google/__init__.py
# -*- coding: utf-8 -*-
# @Author: Sam Zhang
# @Date:   2020-04-12 15:34:31
# @Last Modified by:   Sam Zhang
# @Last Modified time: 2020-04-12 15:41:12

from flask import Blueprint

google = Blueprint('google', __name__, url_prefix='/google/')

from . import views

app/google/views.py
# -*- coding: utf-8 -*-
# @Author: Sam Zhang
# @Date:   2020-04-12 15:36:23
# @Last Modified by:   Sam Zhang
# @Last Modified time: 2020-04-14 11:27:50

from flask import render_template, request, redirect, url_for
from ..utils import google_search
from . import google


@google.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        return redirect(url_for('google.search', q=request.form.get('query'), page=0))
    return render_template('google/index.html')

@google.route('/s/')
def search():
    word = request.args.get('q')
    page = int(request.args.get('page', 0))
    return render_template('google/search.html', keyword=word, cur=page + 1)

@google.route('/s/s/')
def search_s():
    word = request.args.get('q')
    page = int(request.args.get('page', 0))
    results = google_search(word=word, pn=page)
    pages = results[1]
    results = results[0]
    return render_template('google/search_s.html', results=results, pages=pages, keyword=word, cur=page + 1)

app/main/__init__.py
# -*- coding: utf-8 -*-
# @Author: Sam Zhang
# @Date:   2020-04-14 11:07:21
# @Last Modified by:   Sam Zhang
# @Last Modified time: 2020-04-14 11:39:10

from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
# -*- coding: utf-8 -*-
# @Author: Sam Zhang
# @Date:   2020-04-14 11:09:21
# @Last Modified by:   Sam Zhang
# @Last Modified time: 2020-04-14 17:53:28

from flask import render_template, request, current_app, send_file
from . import main
import os
from pytube import YouTube
from uuid import uuid1

@main.route('/')
def index():
    return render_template('index.html')

@main.route('/docs/')
def docs():
    return render_template('docs.html')

@main.route('/about/')
def about():
    return render_template('about.html')

@main.route('/youtube/')
def youtube():
    id = request.args.get('id')
    video_url = 'https://www.youtube.com/watch?v=%s' % id
    youtube = YouTube(video_url)
    video = youtube.streams.filter(res='720p', mime_type='video/mp4')[0]
    uuid = str(uuid1()) + '.mp4'
    path = video.download(os.path.abspath('./app/static'), filename=uuid)
    print(path)
    return send_file(path)

app/templates/about.html
<!-- 
  @Author: Sam Zhang
  @Date:   2020-04-10 20:05:53
  @Last Modified by:   Sam Zhang
  @Last Modified time: 2020-04-14 18:03:01
-->

{% extends 'base.html' %}

{% block title %}关于{% endblock %}

{% block top %}{% endblock %}

{% block content %}
<style>
    body {
        position: relative;
        overflow-x: hidden;
    }

    ul.nav-pills {
        top: 20px;
        position: fixed;
    }

    div.col-8 div {
        height: 100vh;
    }
</style>
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <a class="navbar-brand" href="/">广度搜索 <small class="text-primary">帮助中心</small></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="/docs/">文档</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="https://github.com/samzhangjy/guangdu" target="_blank">GitHub</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/about/">关于</a>
            </li>
        </ul>
    </div>
    <a onclick="changeTheme()" href="" title="换肤"><i class="fa fa-adjust"></i></a>
</nav>

<div class="container" style="margin-top: 80px;">
    <h1>关于</h1>
    <hr>
    <p>
        广度搜索是一个开源的，非商业的搜索引擎。它并非自己产生搜索结果，而是间接地从百度或Google中爬取无广告的搜索结果。<br><br>
        广度搜索的使命是让搜索变得更快捷，简单，而不是从广告中寻找资料。从这个初衷开始，广度搜索就一直在往这个目标前进，努力追寻实用性与快捷性之间的平衡点。如果您会使用Python，也欢迎加入这个项目的开发，使广度向目标更进一步！
    </p>
</div>
{% endblock %}

app/templates/baidu/index.html
<!-- 
  @Author: Sam Zhang
  @Date:   2020-04-10 20:05:45
  @Last Modified by:   Sam Zhang
  @Last Modified time: 2020-04-14 11:33:03
-->

{% extends 'base.html' %}

{% block title %}百度版{% endblock %}

{% block top %}{% endblock %}

{% block content %}
    <a onclick="changeTheme()" href="" class="float-right" style="margin-right: 10%;" title="换肤"><i class="fa fa-adjust"></i></a>
    <div class="container">
        <h1 class="display-4 text-center m-5">
            广度搜索 <small><small><small class="font-italic font-weight-light text-primary">V1.0</small></small></small>
            <small><small><small><small><p></p><p class="font-italic text-center text-primary">Baidu 版</p></small></small></small></small>
        </h1>
        <form method="post">
            <div class="input-group input-group-lg">
                <input class="form-control form-control-lg rounded-0" name="query" type="search" autocomplete="off">
                <button class="btn btn-outline-primary rounded-0" type="submit">广度搜索</button>
            </div>
        </form>
        <hr>
        <p class="text-center">广度搜索也提供<a href="{{ url_for('google.index') }}">Google 版</a> | <a href="/">返回首页</a></p>
    </div>
{% endblock %}

app/templates/baidu/search.html
<!-- 
  @Author: Sam Zhang
  @Date:   2020-04-10 20:05:53
  @Last Modified by:   Sam Zhang
  @Last Modified time: 2020-05-06 18:09:09
-->

{% extends 'base.html' %}

{% block title %}{{ keyword }}{% endblock %}

{% block top %}{% endblock %}

{% block content %}
    <nav class="navbar navbar-dark bg-primary fixed-top shadow shadow-sm">
        <a class="navbar-brand d-none d-lg-block" href="/">广度搜索 <small class="text-light">百度版</small></a>
        <form method="post" class="container search" style="margin-left: 0"
                action="{{ url_for('baidu.index') }}">
            <div class="input-group">
                <input class="form-control" name="query" value="{{ keyword }}" id="search" autocomplete="off" type="search">
                <button class="btn btn-success" type="submit">广度搜索</button>
            </div>
        </form>
        <a onclick="changeTheme()" href="" class="text-white" title="换肤"><i class="fa fa-adjust"></i></a>
    </nav>
    <br><br><br>
    <iframe id="iframe" class="iframe" seamless="seamless" onload="$(this).fadeIn(500); show();" src="{{ url_for('baidu.search_s', q=keyword, page=cur) }}"></iframe>
    <div class="d-flex justify-content-center text-dark" id="load-container">
        <div class="d-flex bg-light p-4 rounded shadow shadow-sm" id="load-sub">
            <div class="spinner-grow text-primary" role="status" id="load">
                <span class="sr-only" id="load-sr">加载中...</span>
            </div>
            <strong id="load-text" class="text-right align-text-bottom" style="margin-left: 20px;">广度正在努力加载中，请耐心等待...</strong>
        </div>
    </div>
    <script>
        function hide() {
            $("#iframe").hide();
            $("#load-container").fadeIn(500);
            $("#load").fadeIn(500);
            $("#load-sr").fadeIn(500);
        }
        function show() {
            $("#load-container").fadeOut(500);
            $("#load").fadeOut(500);
            $("#load-sr").fadeOut(500);
            $("#load-sub").remove();
        }
        window.onload = hide();
    </script>
{% endblock %}

app/templates/baidu/search_s.html
<!-- 
  @Author: Sam Zhang
  @Date:   2020-04-10 20:05:53
  @Last Modified by:   Sam Zhang
  @Last Modified time: 2020-05-06 17:26:20
-->

{% extends 'base.html' %}

{% block title %}{{ keyword }}{% endblock %}

{% block top %}{% endblock %}

{% block content %}
    <style>
        
    </style>
    <script>
        function change(pn) {
            this.parent.location.href = "{{ url_for('baidu.search') }}?q={{ keyword }}&page=" + pn;
        }
    </script>
    {% if pre_results %}
    <div class="container">
        {% if pre_results[0].type == 'total' %}
        <small class="text-muted">广度共找到搜索结果约{{ pre_results[0].result }}个</small>
        <br><br>
        {% endif %}
        {% for result in pre_results %}
        {% if result.type == 'calc' %}
        <div class="container bg-light p-3 pl-4 pr-4 text-dark">
            <h4>{{ result.process }}</h4>
            <p>{{ result.result }}</p>
            <small class="align-text-bottom">广度计算</small>
        </div>
        <hr>
        {% endif %}
        {% endfor %}
    </div>
    {% endif %}
    {% if results %}
    {% for result in results %}
        {% if result.title and result.link %}
            <div class="container">
                {% if result.domain %}
                    <p class="text-success">
                        {{ result.domain }}
                        {% if result.path %}
                            &rsaquo;
                            {% for loc in result.path %}
                                {% if loop.index != result.path | length %}
                                    {{ loc }}
                                    &rsaquo;
                                {% else %}
                                    {{ loc }}
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                    </p>
                {% endif %}
                <h5 id="{{ loop.index }}h5"><a href="{{ result.link }}" target="_blank">{{ result.title }}</a></h5>
                {% if result.time %}<p class="d-inline text-muted">{{ result.time }} &middot; </p>{% endif %}<p class="d-inline text-secondary text-wrap" id="{{ loop.index }}">{% if result.des %}{{ result.des }}{% else %}暂无描述{% endif %}</p>
                <hr>
            </div>
        {% endif %}
    {% endfor %}
    {% else %}
        <div class="container">
            <p>关键词 {{ keyword }} 没有找到搜索结果</p>
        </div>
    {% endif %}
    <div class="container">
        {% for _ in pre_results %}
        {% if _.type == 'related' %}
        <h5>相关搜索</h5>
        <div class="row">
        {% for result in _.results %}
            <div class="col-4 mb-2">
                <a href="{{ result.url }}" class="mb-3" target="_parent">{{ result.text }}</a><br>
            </div>
        {% endfor %}
        </div>
        <br>
        {% endif %}
        {% endfor %}
        <nav>
            <ul class="pagination justify-content-center">
                {% if cur != 0 and cur != 10 %}
                    {% set url = "javascript:change(pn='" + (cur - 1) | string + "')" %}
                {% else %}
                    {% set url = '#' %}
                {% endif %}
                <li class="page-item{% if cur == 0 %} disabled{% endif %}">
                    <a class="page-link" href="{{ url }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% if pages | length <= 10 %}
                    {% for i in pages %}
                        <li class="page-item{% if i == cur %} active{% endif %}"><a class="page-link" href="javascript:change(pn='{{ i }}')">{{ i + 1 }}</a></li>
                    {% endfor %}
                {% endif %}
                {% if cur < pages | length %}
                    {% set url = "javascript:change(pn='" + (cur + 1) | string + "')" %}
                {% else %}
                    {% set url = '#' %}
                {% endif %}
                <li class="page-item{% if cur == pages | length - 1 or cur == 9 %} disabled{% endif %}"{% if cur == 9 %} data-toggle="tooltip" data-placement="top" title="由于性能原因，广度搜索目前仅提供前10页的搜索结果"{% endif %}>
                    <a class="page-link" href="{{ url }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
        <footer class="text-center">
            <hr>
            <p class="text-muted">&copy; 2020 广度搜索 保留所有权利 | 部分搜索结果来自<a href="https://www.baidu.com" target="_blank">百度</a><br><a href="/docs/" target="_blank">文档</a> &middot; <a href="/about/" target="_blank">关于</a> &middot; <a href="https://github.com/samzhangjy/guangdu" target="_blank">GitHub</a></p>
            <!-- <p>当前呈现版本：V</p> -->
        </footer>
    </div>
{% endblock %}

app/templates/base.html
<!-- 
  @Author: Sam Zhang
  @Date:   2020-04-10 20:05:39
  @Last Modified by:   Sam Zhang
  @Last Modified time: 2020-05-06 16:53:39
-->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %} - 广度搜索</title>
    <link href="{{ url_for('static', filename='font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">
    <link rel="icon" href="{{ url_for('static', filename='favicon.png') }}">
    {% set cookie = request.cookies.get('theme') %}
    {% if not cookie %} {% set cookie = 'light' %} {% endif %}
    <link rel="stylesheet" href="{{ url_for('static', filename=cookie + '.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <script src="{{ url_for('static', filename='guangdu.js') }}"></script>
    <script src="{{ url_for('static', filename='jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='bootstrap.bundle.min.js') }}"></script>
</head>
<body {% block body %}{% endblock %}>
    {% block top %}
        <br><br>
    {% endblock %}
    {% block content %}{% endblock %}
    <br><br>
    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
</body>
</html>

app/templates/google/index.html
<!-- 
  @Author: Sam Zhang
  @Date:   2020-04-10 20:05:45
  @Last Modified by:   Sam Zhang
  @Last Modified time: 2020-04-14 11:32:28
-->

{% extends 'base.html' %}

{% block title %}Google版{% endblock %}

{% block top %}{% endblock %}

{% block content %}
    <a onclick="changeTheme()" href="" class="float-right" style="margin-right: 10%;" title="换肤"><i class="fa fa-adjust"></i></a>
    <div class="container">
        <h1 class="display-4 text-center m-5">
            广度搜索 <small><small><small class="font-italic font-weight-bold text-primary">V1.0</small></small></small>
            <small><small><small><small><p></p><p class="font-italic text-center text-warning">Google 版</p></small></small></small></small>
        </h1>
        <form method="post">
            <div class="input-group input-group-lg">
                <input class="form-control form-control-lg rounded-0" name="query" type="search" autocomplete="off">
                <button class="btn btn-outline-primary rounded-0" type="submit">广度搜索</button>
            </div>
        </form>
        <hr>
        <p class="text-center">广度搜索也提供<a href="{{ url_for('baidu.index') }}">百度版</a> | <a href="/">返回首页</a></p>
    </div>
{% endblock %}

app/templates/google/search.html
<!-- 
  @Author: Sam Zhang
  @Date:   2020-04-10 20:05:53
  @Last Modified by:   Sam Zhang
  @Last Modified time: 2020-05-06 17:25:27
-->

{% extends 'base.html' %}

{% block title %}{{ keyword }}{% endblock %}

{% block top %}{% endblock %}

{% block content %}
    <nav class="navbar navbar-dark bg-primary fixed-top shadow shadow-sm">
        <a class="navbar-brand d-none d-lg-block" href="/">广度搜索 <small class="text-warning">Google版</small></a>
        <form method="post" class="container search" style="margin-left: 0"
                action="{{ url_for('google.index') }}">
            <div class="input-group">
                <input class="form-control" name="query" value="{{ keyword }}" id="search" autocomplete="off" type="search">
                <button class="btn btn-success" type="submit">广度搜索</button>
            </div>
        </form>
        <a onclick="changeTheme()" href="" class="text-white" title="换肤"><i class="fa fa-adjust"></i></a>
    </nav>
    <br><br><br><br>
    <iframe id="iframe" onload="$(this).fadeIn(500); show()" src="{{ url_for('google.search_s', q=keyword, page=cur) }}" class="iframe" seamless="seamless"></iframe>
    <div class="d-flex justify-content-center text-dark" id="load-container">
        <div class="d-flex bg-light p-4 rounded shadow shadow-sm" id="load-sub">
            <div class="spinner-grow text-primary" role="status" id="load">
                <span class="sr-only" id="load-sr">加载中...</span>
            </div>
            <strong id="load-text" class="text-right align-text-bottom" style="margin-left: 20px;">广度正在努力加载中，请耐心等待...</strong>
        </div>
    </div>
    </div>
    <script>
        function hide() {
            $("#iframe").hide();
            $("#load-container").fadeIn(500);
            $("#load").fadeIn(500);
            $("#load-sr").fadeIn(500);
            $("#load-text").fadeIn(500);
            $("#load-sub").fadeIn(500);
        }
        function show() {
            $("#load-container").fadeOut(500);
            $("#load").fadeOut(500);
            $("#load-sr").fadeOut(500);
            $("#load-sub").remove();
            $("#load-text").fadeOut(500);
        }
        window.onload = hide();
    </script>
{% endblock %}

app/templates/google/search_s.html
<!-- 
  @Author: Sam Zhang
  @Date:   2020-04-10 20:05:53
  @Last Modified by:   Sam Zhang
  @Last Modified time: 2020-05-06 16:45:24
-->

{% extends 'base.html' %}

{% block title %}{{ keyword }}{% endblock %}

{% block top %}{% endblock %}

{% block content %}
    <script>
        function change(pn) {
            this.parent.location.href = "{{ url_for('google.search') }}?q={{ keyword }}&page=" + pn;
        }
    </script>
    {% if results %}
    {% for result in results %}
        {% if result.title and result.link %}
            <div class="container">
                {% if result.domain %}
                    <p class="text-success">
                        {{ result.domain }}
                        {% if result.path %}
                            &rsaquo;
                            {% for loc in result.path %}
                                {% if loop.index != result.path | length %}
                                    {{ loc }}
                                    &rsaquo;
                                {% else %}
                                    {{ loc }}
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                    </p>
                {% endif %}
                <h5 id="{{ loop.index }}h5"><a href="{{ result.link }}" target="_blank">{{ result.title }}</a></h5>
                {% if result.time %}<p class="d-inline text-muted">{{ result.time }} &middot; </p>{% endif %}<p class="d-inline text-secondary" id="{{ loop.index }}">{% if result.des %}{{ result.des }}{% else %}暂无描述{% endif %}</p>
                <hr>
            </div>
        {% endif %}
    {% endfor %}
    {% else %}
        <div class="container">
            <p>关键词 {{ keyword }} 没有找到搜索结果</p>
        </div>
    {% endif %}
    <div class="container">
        <nav>
            <ul class="pagination justify-content-center">
                {% if cur != 1 and cur != 10 %}
                    {% set url = "javascript:change(pn='" + (cur - 3) | string + "')" %}
                {% else %}
                    {% set url = '#' %}
                {% endif %}
                <li class="page-item{% if cur == 2 %} disabled{% endif %}">
                    <a class="page-link" href="{{ url }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% if pages | length <= 10 %}
                    {% for i in pages %}
                        <li class="page-item{% if i == cur - 1 %} active{% endif %}"><a class="page-link" href="javascript:change(pn='{{ i - 1 }}')">{{ i }}</a></li>
                    {% endfor %}
                {% endif %}
                {% if cur < pages | length %}
                    {% set url = "javascript:change(pn='" + (cur - 1) | string + "')" %}
                {% else %}
                    {% set url = '#' %}
                {% endif %}
                <li class="page-item{% if cur == 11 or cur == pages | length + 1 %} disabled{% endif %}"{% if cur == 11 %} data-toggle="tooltip" data-placement="top" title="由于性能原因，广度搜索目前仅提供前10页的搜索结果"{% endif %}>
                    <a class="page-link" href="{{ url }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
        <footer class="text-center">
            <hr>
            <p class="text-muted">&copy; 2020 广度搜索 保留所有权利 | 部分搜索结果来自<a href="https://www.google.com">Google</a><br><a href="/docs/" target="_blank">文档</a> &middot; <a href="/about/" target="_blank">关于</a> &middot; <a href="https://github.com/samzhangjy/guangdu" target="_blank">GitHub</a></p></p>
        </footer>
    </div>
{% endblock %}

app/templates/index.html
<!-- 
  @Author: Sam Zhang
  @Date:   2020-04-14 11:11:22
  @Last Modified by:   Sam Zhang
  @Last Modified time: 2020-04-14 11:33:23
-->

{% extends 'base.html' %}

{% block title %}首页{% endblock %}

{% block top %}{% endblock %}

{% block content %}
    <div class="container">
        <nav class="nav nav-pills flex-column flex-sm-row" id="pills-tab" role="tablist" style="margin-top: 3%;">
            <a class="flex-sm-fill text-sm-center nav-link active" id="baidu-tab" data-toggle="pill" href="#pills-baidu" role="tab" aria-controls="baidu" aria-selected="true">百度版</a>
            <a class="flex-sm-fill text-sm-center nav-link" id="google-tab" data-toggle="pill" href="#pills-google" role="tab" aria-controls="google" aria-selected="false">Google版</a>
        </nav>
    </div>
    <div class="tab-content" id="pills-tabContent">
        <div class="tab-pane fade show active" id="pills-baidu" role="tabpanel" aria-labelledby="pills-baidu-tab">
            <a onclick="changeTheme()" href="" class="float-right" style="margin-right: 10%;" title="换肤"><i class="fa fa-adjust"></i></a>
            <div class="container">
                <h1 class="display-4 text-center m-5">
                    广度搜索 <small><small><small class="font-italic font-weight-light text-primary">V1.0</small></small></small>
                    <small><small><small><small><p></p><p class="font-italic text-center text-primary">百度版</p></small></small></small></small>
                </h1>
                <form method="post" action="{{ url_for('baidu.index') }}">
                    <div class="input-group input-group-lg">
                        <input class="form-control form-control-lg rounded-0" name="query" type="search" autocomplete="off">
                        <button class="btn btn-outline-primary rounded-0" type="submit">广度搜索</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="tab-pane fade" id="pills-google" role="tabpanel" aria-labelledby="pills-google-tab">
            <a onclick="changeTheme()" href="" class="float-right" style="margin-right: 10%;" title="换肤"><i class="fa fa-adjust"></i></a>
            <div class="container">
                <h1 class="display-4 text-center m-5">
                    广度搜索 <small><small><small class="font-italic font-weight-light text-primary">V1.0</small></small></small>
                    <small><small><small><small><p></p><p class="font-italic text-center text-warning">Google版</p></small></small></small></small>
                </h1>
                <form method="post" action="{{ url_for('google.index') }}">
                    <div class="input-group input-group-lg">
                        <input class="form-control form-control-lg rounded-0" name="query" type="search" autocomplete="off">
                        <button class="btn btn-outline-primary rounded-0" type="submit">广度搜索</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}